baseURL = "https://johnlian.net/"
min_version = "0.152.2"
languageCode = "en-us"
title = "John Lian"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[pagination]
  pagerSize = 9
googleAnalytics = ""
enableRobotsTXT = true
pygmentsCodefences = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["css/style.css"]
  favicon = "/favicon.ico"
  description = "John Lian's personal website"
  wikipedia = "https://en.wikipedia.org/wiki/User:Lianguanlun"
  github = "https://github.com/jlian"
  linkedin = "https://www.linkedin.com/in/jlian1/"
  instagram = "https://www.instagram.com/jlian.irl/"
  twitter = "https://twitter.com/jlian"
  youtube = "https://www.youtube.com/@lianguanlun"
  background_color_class = "bg-black"
  body_classes = "sans-serif"
  text_size = "fw3 f5 f5-l"
  featured_image = "/images/seattle.jpg"
  default_featured_image = "/images/default-featured.jpg"
  recent_posts_number = 6
  mainSections = ["posts"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github"
